baseURL = 'https://roehrs.ai'
languageCode = 'en-us'
title = 'Roehrs.ai'
theme= 'paige'
publishDir = 'docs'
ignoreLogs = ['warning-goldmark-raw-html']


[params]
paige.menu_style = "pills"

[params.paige.site]
disable_breadcrumbs = true
disable_copyright = false
disable_credit = true

disable_description = false
disable_license = false
disable_menu = false
disable_title = false



[params.paige.list_page]
disable_authors = false
disable_collections = false
disable_date = false
disable_description = false
disable_keywords = true
disable_pages = false
disable_reading_time = true
disable_sections = false
disable_series = false
disable_summary = false
disable_title = false

[params.paige.page]
disable_alert = false
disable_authors = false
disable_date = false
disable_description = false
disable_edit = false
disable_history = false
disable_keywords = false
disable_next = false
disable_prev = false
disable_reading_time = true
disable_series = false
disable_title = true
disable_toc = false


[params.paige.search]
disable = false # Exclude the page from search

[[module.imports]]
path = "github.com/willfaught/paige"



