baseURL = 'https://roehrs.ai'
languageCode = 'en-us'
title = 'Roehrs.ai'
theme= 'paige'
publishDir = 'docs'
ignoreLogs = ['warning-goldmark-raw-html']


[params]
paige.site.disable_credit = 1


[[module.imports]]
path = "github.com/willfaught/paige"



